name: lapor_balongmojo
description: "Aplikasi Layanan Masyarakat Desa Balongmojo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0-290.4.beta

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Utilities
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  image_picker: ^1.2.1

  # State Management
  provider: ^6.1.5+1

  # Networking
  http: ^1.6.0
  http_parser: ^4.1.2

  # Local Storage (Token)
  flutter_secure_storage: ^9.2.4

  # Firebase & Notifications
  firebase_core: ^4.3.0
  firebase_messaging: ^16.1.0
  flutter_local_notifications: ^19.5.0

  shared_preferences: ^2.5.3
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/app_icon.jpeg" 
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/icon/