version: '3.8'

services:
  # Service Database
  db:
    image: mysql:8.0
    container_name: lapor_balongmojo_db
    restart: always  # Diperbarui sesuai Hari 27 (Auto Restart)
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'lapor_balongmojo'
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql

  # Service API (Backend)
  api:
    container_name: lapor_balongmojo_api
    build: .
    restart: always  # Diperbarui sesuai Hari 27 (Auto Restart)
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: 'db'
      DB_USER: 'root'
      DB_PASSWORD: 'password'
      DB_DATABASE: 'lapor_balongmojo'
      JWT_SECRET: 'password'
    
    # Command untuk development (agar hot-reload jalan)
    command: npm run dev
    
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      # Mapping folder uploads agar gambar tidak hilang saat container direstart
      - ./public/uploads:/usr/src/app/public/uploads

volumes:
  db_data: